#ifndef TSPN_CONSTANTS_H
#define TSPN_CONSTANTS_H

#define INSTANCE_TYPE_2D 1
#define INSTANCE_TYPE_3D 2

#define OVERLAP_0_1 0.1
#define OVERLAP_0_25 0.25
#define OVERLAP_0_5 0.5
#define OVERLAP_1_0 1.0
#define OVERLAP_1_5 1.5

#define BRANCHING_RULE_V1 1
#define BRANCHING_RULE_SB 2

#define BRANCHING_STRATEGY_DFS 1
#define BRANCHING_STRATEGY_BFS 2
#define BRANCHING_STRATEGY_BeFS 3

#define ROOT_SELECTION_1 1
#define ROOT_SELECTION_2 2
#define ROOT_SELECTION_3 3

#endif //TSPN_CONSTANTS_H
